# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectrecognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.ImageField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
